global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # 모니터링

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
